### PR TITLE
Remove all `FormattedMessage` references and use existing `gettext` approach

### PR DESCRIPTION
**Pull request by AparnaKarve**
Remove all `FormattedMessage` references and use existing `gettext` approach.

@priley86 As discussed, I have made the above change.

### CODE REVIEW

**Comment by michaelkro** [comment]
manageiq_v2v_plugin

**Comment by priley86** [comment]
looks great @AparnaKarve! will wait for CI.

@michaelkro @mturley ok to merge?

**Comment by michaelkro** [comment]
@priley86 I think there are just a few missed strings.  Check out screenshot above

**Comment by AparnaKarve** [comment]
@michaelkro Can you re-verify?

With the browser set to Chinese, you should see this -
screen shot 2018-02-09 at 12 27 21 pm

and otherwise -
screen shot 2018-02-09 at 12 27 56 pm

**Comment by michaelkro** [comment]
I'm looking at the `Plan Wizard`.  I apologize if that is out of scope for this PR, I'm just clicking around lol

**Comment by AparnaKarve** [comment]
you are right! :) - the plan wizard is not showing up as expected.
Looking into it...

**Comment by michaelkro** [comment]
Ok cool :) 
One more @AparnaKarve, this is the loading screen for the Plan Wizard
fullscreen_2_9_18__3_29_pm

**Comment by AparnaKarve** [comment]
@michaelkro Addressed in 90f1986

**Comment by michaelkro** [comment]
@AparnaKarve Looks good!

**Pull request merged**
