### PR TITLE
update to pf-react 2.0

### PR DESCRIPTION
**Pull request by priley86**
Updates pf-react to 2.0 and upgrades `Wizard` in v2v.

For some reason bootstrap-select `1.13.0` now conflicts w/ the PF version used in miq-classic/v2v, so I have locked to `~1.12.4` for now.

Do not merge yet.... requires this PR in PF-React for `onExited` callback first.
https://github.com/patternfly/patternfly-react/pull/316

**UPDATED to 2.2**: should be g2g now...

### CODE REVIEW

**Comment by priley86** [comment]
ok ... cherry picked #233 and updated spinner location. Would love to pull these commits into the branch i've started for Vince...

lemme know if any issues here.

screen shot 2018-04-20 at 8 49 30 am

**Comment by priley86** [comment]
ok - looks like we need to make the same change to the Migrations in Progress cards... do you mind taking a stab at this @michaelkro ?

**Comment by priley86** [comment]
fixed! woohoo!

**Comment by AllenBW** [comment]
WOOOH (cept travis hates you)

**Comment by priley86** [comment]
omg travis stop it!!!

**Comment by priley86** [comment]
🛥  🛥 🛥  🛥 🛥  🛥 

⛵️ ⛵️ ⛵️ ⛵️ ⛵️ ⛵️ ⛵️ 

🚢 🚢 🚢 🚢 🚢 🚢 🚢 

⚓️ ⚓️ ⚓️ ⚓️ ⚓️ ⚓️ ⚓️

**Comment by AllenBW** [comment]
Remember future Allen, refresh `node_modules`...

**Pull request merged**
