### PR TITLE
Create Overview Infrastructure Mappings List View

### LINKED ISSUE #152: Create Overview Infrastructure Mappings List View
Per the new UX, we will be able to visualize Infrastructure Mappings as a list view on the Overview Screen.

* include new Empty State view for when no mappings exist

### PR DESCRIPTION
**Pull request by AllenBW**
fixes #152

Side note, the `associated plans` stuff matches mock, but isn't live, can pull it if we wanta be without notional data

this could use a bitta dry-ing butttttt thought it best to throw up the closest thing to working as soon as possible

### latest ss
screen shot 2018-04-13 at 5 23 33 pm

### this is a goodie, but an oldie
pfselect

### CODE REVIEW

**Comment by AllenBW** [comment]
@priley86 okie dokie, changes, hit me with em! <3 😋

**Comment by AllenBW** [comment]
ugh. rebasing 😭

**Comment by priley86** [comment]
looking good @AllenBW - taking a peek here in just a sec... really appreciate this!!

**Comment by priley86** [comment]
this is looking great 😻  - i'd be ok w/ merging later today/early Monday once you are comfortable? And filing additional issues for next sprint...

Only minor design nit I have is it seems the list expansion details are aligned a bit different than PF detail alignments I have seen in the past. I don't seem to have a lot of great examples though...

Maybe look at adding some spacing more like the detail expansion in our compound expansion example?
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-view-compound-expansion.html

There are not any good examples of detail alignment in PF React yet it doesn't seem...

**Comment by AllenBW** [comment]
@priley86  Good nit, BUT I would say thats a thing to be addressed in pfr.  If you notice across libraries and even in pf guidance, there are inconsistencies with a list view item with dropdown **but no checkbox**

I believe https://rawgit.com/patternfly/patternfly-ng/master-dist/dist-demo/#/list is where we want pfr to be: 
screen shot 2018-04-13 at 9 32 40 am

but if you notice, http://www.patternfly.org/pattern-library/content-views/list-view/#code, there are no examples of expand without a checkbox....

present state matches what can be found in pfa:  
screen shot 2018-04-13 at 9 34 02 am


@serenamarie125 thinkin the pfn project has the desired styling, more spacing around the 🥕 and a horizontal bar separating the item actions and item text.. if this is sooooooo then I can get to gettin to updating pfr to look like pfn

* PFR - patternfly react 
* PFN - patternfly next
* PFA - patternfly angular
* PWTF - patternfly what the fq

**Comment by AllenBW** [comment]
@priley86 DRY-ied this out, ready to go when you are.

**Comment by priley86** [comment]
yes - so many variations ^^ ... cross referenced: https://github.com/patternfly/patternfly-react/issues/158

**Comment by AllenBW** [comment]
@serenamarie125 any idea what those spacings are? do we have this live somewhere i can get a sense of how everything spaces out?

**Comment by serenamarie125** [comment]
@AllenBW do you need spacings?  My thought is that you have 3 columns of label/value pairs.

**Comment by serenamarie125** [comment]
@AllenBW How about 4-4-4 split, and have the titles above the values rather than showing label/value pairs on the same line.  Make sense?

screen shot 2018-04-13 at 4 58 49 pm

**Comment by AllenBW** [comment]
wooooooooooh ok so here were go! 
screen shot 2018-04-13 at 5 23 33 pm


@serenamarie125 @priley86 ya'll wanta do anything else to this ?

**Comment by AllenBW** [comment]
can close this as #212 grabs the contents of this pr

**Pull request closed without merging**
