### PR TITLE
Migration nav item should not have any sub items & should show what's currently in Overview

### LINKED ISSUE #161: Migration nav item should not have any sub items & should show what's currently in Overview
Initially we thought that there would be 3 sub items under Migration, but Vince has come up with a great way to have everything on a single page.  

This issue should consist of:
- Removing sub items from the **Migration** nav item
- Display current **Overview** content when selecting **Migration**

NOTE: In the future, we might want to add it back as new features are added that will necessitate a separate mappings page and nav sub items. So maybe just comment out the code?

### PR DESCRIPTION
**Pull request by AllenBW**
~[requires #3683 before this can get in...
](https://github.com/ManageIQ/manageiq-ui-classic/pull/3683)~
~closes #161 so lets **WIP** it till then... but please do feedback ah meeeeee so this can be made as perfect as possible for as soon as #3683 makes a move~

looks like #3683 made it in! this is g2g

### so whats this look like? 
migration

### updated breadcrumb
screen shot 2018-04-02 at 7 37 37 am

### ~but gotta a question...~ no more questions! 
screen shot 2018-03-26 at 1 46 21 pm

~@serenamarie125 @vconzola yah want the breadcrumb collapsed as well?~

~@priley86 that other component we dont look at `InfrastructureMappings`, yah want it cleaned up in this work as well?~

### CODE REVIEW

**Comment by priley86** [comment]
@AllenBW we are targeting sprint6 branch. Please feel free to update/remove react router routes accordingly. Thanks!!

**Comment by AllenBW** [comment]
@serenamarie125 @priley86 this is g2g whenever ya'll are!

**Comment by priley86** [comment]
Thanks a lot @AllenBW - this was more than expected ;) 

Code looks fine. Just waiting on breadcrumb confirmation @vconzola @serenamarie125 .

**Comment by AllenBW** [comment]
@priley86 on it!

**Comment by AllenBW** [comment]
screen shot 2018-04-02 at 7 37 37 am


@priley86 @vconzola updated breadcrumb as requested

**Comment by priley86** [comment]
thanks @AllenBW 🥇 

i will go ahead and merge... let's target the PF upgrade in PF-React next if you are up to investigating that...hopefully it resolves the Breadcrumbs design (this was mentioned during the last community meeting i believe).

**Comment by AllenBW** [comment]
@priley86... yeah can up the dep, thoughts on updating the whole slew of em vs just the one?

**Pull request merged**
