### PR TITLE
Refactor #removeNode in DatastoresStepForm

### PR DESCRIPTION
**Pull request by michaelkro**
### Adds unit tests
* Test around removal of nodes
* Test around target datastore capacity validation

### Refactor `removeNode()`
* Extract map() callbacks to helpers
* Consolidate repeated code

### CODE REVIEW

**Comment by priley86** [comment]
this is looking much better to me, very nice ;) 

maybe you can also give a simple input/output snapshot for those static helper functions (`removeSourceDatastore` and `updateMappings`) some place? Pretty good example of snapshotting w/ Ezyme recently introduced [here](https://github.com/patternfly/patternfly-react/pull/258) in pf-react. I like the approach a lot...

**Comment by priley86** [comment]
@michaelkro can you rebase this one and target `sprint5`?

**Comment by michaelkro** [comment]
@priley86 rebased + re-targeted 👍

**Comment by priley86** [comment]
thanks!

**Pull request merged**
