### PR TITLE
mapping wizard e2e

### PR DESCRIPTION
**Pull request by priley86**
this PR does the following:

* lifts mapping wizard state out of ModalWizard/ModalWizardStateProvider abstractions into MappingWizard (and I think we can potentially lift it further to redux later if desired and made into a common redux contained component).
* makes use of the common the ModalWizardBody introduced - however, I think it can probably be converted to a stateless component if desired (what we have works for now though). I question if this is common enough to introduce into pf-react (since we are entailing the loading/body design), but it may be worth considering. This would not necessarily be common if one used the sidebar, however it is still a useful helper and could be made more common for other apps.
* creates final POST body to be posted for creating transformation mappings and calls the API
* completes e2e flows for wizard (connecting step 4 #65 introduced yesterday and completing #31 (step 5).
* adds the "Continue to Plan" wizard function and auto selects a mapping on the plan wizard once continuing through 

some additional things I'd like to tackle alongside #63 after this PR merges : 
* finalize validation of next button on steps 3, 4
* finish the warning modals for steps 3, 4 discussed yesterday

Results loading:
screen shot 2018-02-27 at 1 19 12 am

Results completed (w/ continue):
screen shot 2018-02-27 at 3 31 19 pm

Continue to Plans:
screen shot 2018-02-27 at 3 31 28 pm

### CODE REVIEW

**Comment by priley86** [comment]
cc: @michaelkro @AparnaKarve @mturley please let me know if you have any issues here...

**Comment by michaelkro** [comment]
networks-step-dropdown

**Comment by michaelkro** [comment]
select-source-cluster

**Comment by michaelkro** [comment]
create-mapping

**Comment by michaelkro** [comment]
add-mapping

**Comment by michaelkro** [comment]
fullscreen_2_27_18__8_46_am

**Comment by michaelkro** [comment]
fullscreen_2_27_18__8_59_am

**Comment by priley86** [comment]
just now realized - my screenshot is not showing the Infra Mapping name "All mappings in [] have been mapped"... fixing this super easy one now...and reuploading the screenshot.

**Comment by priley86** [comment]
updated...and passed via redux instead.

**Comment by michaelkro** [comment]
Looks good!  Mapping name is showing up now 👍

**Pull request merged**
