### PR TITLE
CSV fixes, validation and VM Table updates

### PR DESCRIPTION
**Pull request by AparnaKarve**
Includes -

- CSV parsing based on the header row
- i18n considerations
- Error screens triggered as a result of CSV parsing 
- VM Table adjustments - added a new column to indicate VM Row validity with status displayed in popovers

Fixes https://github.com/priley86/miq_v2v_ui_plugin/issues/206

(MIQ backend PRs are still merge pending)

---------------------------------

Validation Error screens with error descriptions -

screen shot 2018-04-20 at 2 05 15 pm

screen shot 2018-04-20 at 2 05 29 pm

screen shot 2018-04-20 at 2 05 43 pm

-----------------------------------------

VM Table with Popovers for status

screen shot 2018-04-30 at 6 56 25 am

screen shot 2018-04-30 at 6 56 35 am

screen shot 2018-04-30 at 6 57 49 am

### CODE REVIEW

**Comment by priley86** [comment]
this looks fantastic to me @AparnaKarve - but will wait for @serenamarie125 and @vconzola to weigh in. It looks like you also had some more questions for them in the issue [here](https://github.com/priley86/miq_v2v_ui_plugin/issues/206#issuecomment-382833858).

If you have additional time this sprint, would be great to tackle some feedback we received at the demo last week..

opened #240 for this:
https://github.com/priley86/miq_v2v_ui_plugin/issues/240

**Comment by priley86** [comment]
also - would you mind posting a sample csv that you've been testing here for the rest of us?

**Comment by priley86** [comment]
@serenamarie125 re: # 1... i was just following the PF React example there (so it was padded there) initially. Removing the space could be achieved by removing the `sm-col-12` though.. (the Grid.Row) in React jsx...

screen shot 2018-04-23 at 9 13 19 am

thoughts?

**Comment by AparnaKarve** [comment]
Based on the above comment, it looks like some of these styling things need to be resolved on the PF React side, if at all?

@priley86 Here is a sample csv that I have been using for my testing -

```csv
Name,Host,UID,provider
cfmetest67,esxi1,421fcbfc-3b4c-46d6-c7f4-da8a27e0243b,vCenter
demo-infoblox,esxi1,421fd6d6-1788-77f8-f53a-6db47ce65175,vCenter
namwrncld037,esxi1,421f6d94-5f9c-5f80-90ca-08ba516c45ee,vCenter
namwrncld055,esxi1,421f2b21-9dff-488d-f47e-0a7c7707997d,vCenter
nate-ocp-test,esxi1,421f5d50-5746-5f22-8d06-7c55f49e41b1,vCenter
```

Since we are all using the same DB(I assume), it should work for all of us.

**Comment by AparnaKarve** [comment]
The API PR https://github.com/ManageIQ/manageiq-api/pull/358 should be merged soon.
This PR can be merged right after that.

The wording of the VM validation reason strings is now being controlled by us (as in, the frontend)
@vconzola Please suggest any wording changes here - https://github.com/priley86/miq_v2v_ui_plugin/pull/239/commits/b023ef8ac3f9ee747e285350a8c676c2b397c6ea

**Comment by priley86** [comment]
it would be nice to have this merged in order to test #260 e2e. We can revisit any table design later, merging this one for now.

**Comment by bthurber** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1564239

**Pull request merged**
