### PR TITLE
Refactor both wizards to use new WizardPattern.Stateful

### PR DESCRIPTION
**Pull request by mturley**
Note to reviewers: This PR depends on https://github.com/patternfly/patternfly-react/pull/268, and attempts to pull it in with the `package.json` change. That change should be reverted when we can release and upgrade patternfly-react instead of pointing at that `modal-wizard` branch. To get it working (if npm doesn't figure it out for you with this change, it seems to do so sometimes):

```
cd miq_v2v_ui_plugin/node_modules
rm -rf patternfly-react
git clone git@github.com:mturley/patternfly-react.git
cd patternfly-react
git checkout modal-wizard
npm install
```

That `npm install` at the end is important to make sure you have the different version of patternfly-react built. You should do that before you run `rake update:ui`.

### CODE REVIEW

**Comment by mturley** [comment]
Currently, when you open up one of the wizards and click Next, you get some sort of React-flavored infinite loop. I give up for tonight, because it's tomorrow now.

screen shot 2018-03-21 at 4 46 18 am

**Comment by mturley** [comment]
@priley86 your help with the above head-scratcher would be greatly appreciated.

**Comment by priley86** [comment]
@mturley will dive in shortly w/ you...

**Comment by michaelkro** [comment]
I think that infinite loop is b/c `MappingWizardBody.js` no longer exists.  That's where we had to patch that `redux-form` issue

https://github.com/priley86/miq_v2v_ui_plugin/pull/42#discussion_r168798062

**Comment by mturley** [comment]
Oh crap, did I forget to delete a reference to it? Oh.. I see. The shouldComponentUpdate :( but my pure functions...

**Comment by michaelkro** [comment]
Datastores step warning alerts (for exceeding disk space capacity) are not showing up

**Comment by mturley** [comment]
It does still appear to only affect the mapping wizard @michaelkro. So I think you're right. I'll put that back in the

**Comment by mturley** [comment]
Wow, @michaelkro thanks. I juuuust got it to actually run late last night, so I clearly haven't tested it thoroughly yet. I'll take on your list tomorrow morning!

**Comment by mturley** [comment]
Still working on bugfixes and cleanup here, I'll push more commits either later tonight or tomorrow. Need to run for the day soon.

**Comment by vojtechszocs** [comment]
@mturley @priley86 

> This PR depends on patternfly/patternfly-react#268, and attempts to pull it in with the `package.json` change. That change should be reverted when we can release and upgrade patternfly-react instead of pointing at that `modal-wizard` branch.

```
$ yarn info patternfly-react dist-tags
yarn info v1.3.2
{ latest: '1.16.4' }
```

`patternfly-react` package currently doesn't use the `next` [dist-tag](https://docs.npmjs.com/cli/dist-tag). dist-tag is basically an alias for a specific version which might change over time. The `latest` dist-tag typically marks the latest stable release.

In `patternfly-react`, you might consider using the `next` dist-tag to make new or experimental features/changes available to other projects, before those are made part of a stable release. In such case, you could modify your consuming project's `package.json` like so:

```diff
-    "patternfly-react": "^1.11.0",
+    "patternfly-react": "next",
```

**Comment by priley86** [comment]
@vojtechszocs thanks a lot for sharing this - hadn't started looking into npm dist-tags until now. Very useful feature...

It looks like semantic-release currently supports the `publishConfig.tag` feature. More on that here:
https://github.com/semantic-release/semantic-release/issues/511#issuecomment-343799031

Basically we can specify the npm dist-tag on publish, however, it we change that to "next", we'd have to manually re-link "latest" when we decide it's ready. Not a bad a process, but it would be more ideal to be able to support both "latest" and "next" working concurrently. That is exactly what is being discussed here:
https://github.com/semantic-release/semantic-release/issues/563 

To avoid changing the semantic-release process for now, I have gone ahead and manually published `patternfly-react@1.17.0` under the `next` tag:

Steps were:
1. checkout @mturley 's `modal-wizard` branch
2. modify package.json version manually to our reference our next minor `1.17.0`:
```
{
  "name": "patternfly-react",
  "version": "1.17.0"
...
```
3. run `npm run build` to ensure `dist` is built
4. Publish the branch with dist-tag `next`:
```
npm publish --tag next
```

And you now have it...
```
| ~/GitHub/patternfly-react @ priley-OSX (priley)
| => npm info patternfly-react dist-tags
{ latest: '1.16.4', next: '1.17.0' }
```

So yes, you should be able to pull down @mturley 's branch with `npm install patternfly-react@next`... and future publishes from the `master` branch will skip over this version automatically when publishing.

That being said, @mturley 's changes are breaking changes to Wizard and this a pretty big jump forward, so for that reason, I propose we bump to the next major version in pf-react when that PR is merged. I'll go back to that PR and add some commentary about this now...

**Comment by priley86** [comment]
p.s. apologies for late response... i was on P.T.O yesterday ;)

**Comment by mturley** [comment]
> That being said, @mturley 's changes are breaking changes to Wizard and this a pretty big jump forward, so for that reason, I propose we bump to the next major version in pf-react when that PR is merged. I'll go back to that PR and add some commentary about this now...

Aww yeah. You know your PR is good when it causes a major version bump :) (jk)

**Comment by priley86** [comment]
> Aww yeah. You know your PR is good when it causes a major version bump :) (jk)
Yes, I think it was good to showcase a higher level abstraction in patternfly-react (i.e. Wizard step logic) and begin constructing patterns there to share with others. This saves code on the application end in the long run, however it also means we have to do our best to keep the abstractions flexible and consumable for everyone. The downside to this is when changes get introduced to a high level pattern, we have to ensure it will not break others, but i'm OK w/ this as long as we communicate this well. Many design libraries you see on the web today keep away from implementing the stateful patterns (and just provide simple building blocks the user has to combine themselves), however I think it is fine to do this as long as they are indicated as such and remain flexible. We should just caution those and introduce them as we have time (often after iterating on them first downstream like we did here).

As you know, the breaking change this time was more b/c of the design intention change around embedded wizards. Knowing the intention changed there, we were able to simplify the code even further...

I'm happy w/ where we've landed w/ this if you are ;-> ... I'd like to finish resolving the issues in this PR and the Wizard pattern in PF-React over the course of this week in Raleigh if there is any additional time.

**Comment by mturley** [comment]
@priley86 I am happy where we've landed on this too. Let's try and get it wrapped up so we can move on! Perhaps merging this PR first, targeting `patternfly-react@next`, would be a good idea since the robust testing we still need in the pf-react PR may take a little longer. (and merging this will unblock the rest of the v2v work that i'm getting anxious about not having started yet...)

**Comment by mturley** [comment]
@michaelkro, my next order of business (if I end up with free time this week in Raleigh) is to address your checklist above. I haven't forgotten!

**Comment by priley86** [comment]
yes - i think we should resolve @michaelkro 's issues first... otherwise we break some very important features. Maybe you can chat w/ him today! We can continue to work in parallel on other issues.

**Comment by vojtechszocs** [comment]
> and future publishes from the master branch will skip over this version automatically when publishing.

I'm not too familiar with `semantic-release` but in general, `next` should be always "same or ahead of" `latest` in terms of commits included in the dist-build.

Whenever you decide to release new *stable* version of `patternfly-react`, you can update both `latest` and `next` dist-tags to point to that version. As more changes land in `master` branch (out of which you'd branch/tag stable releases), you can update `next` dist-tag as needed.

The value of `next` dist-tag lies in consumer's ability to test new components/features before they land in a stable release. Some consumer projects rely on old'ish versions of `patternfly-react` and update slowly. But some other consumer projects like to stay up-to-date by updating more often (=> avoid big bang updates).

With `next` dist-tag effectively being a pre-release, you could also consider organizing community events to hack around new components/features :man_technologist: :rocket:

> That being said, @mturley 's changes are breaking changes to Wizard and this a pretty big jump forward, so for that reason, I propose we bump to the next major version in pf-react when that PR is merged.

:+1: 

> Many design libraries you see on the web today keep away from implementing the stateful patterns (and just provide simple building blocks the user has to combine themselves), however I think it is fine to do this as long as they are indicated as such and remain flexible. We should just caution those and introduce them as we have time (often after iterating on them first downstream like we did here).

Those patterns, representing common applications of basic building blocks aligned with PatternFly standards, usually originate in consumer projects. I feel that the UI library's primary focus should be on having rock-solid building blocks, but patterns are also very useful and if we see an opportunity for a commonly needed/used pattern, we should take that opportunity. Worst case, people can always fall back to using the building blocks.

**Comment by priley86** [comment]
@mturley i feel comfortable merging the PF-R PR for the Wizard if you can make the last round of updates there. Then we can phase in those changes into v2v. thanks so much!!!

**Comment by mturley** [comment]
Okay guys. 😔  😑  😐 I'm "starting over" this PR a second time.

Not actually redoing any work, I will mostly be moving code around that is already written. But @priley86 and I discussed the challenges I've hit trying to get this stuff together and merged, and we decided the wholesale make-everything-perfect approach was, of course, flawed from the beginning. So I'm going to roll out this stuff as a few smaller Pull Requests. Here's my new plan, and hopefully I can get it all executed today/tomorrowish. Ideally, I'll get all of this reviewed and in by the end of the week, but the idea is that these pieces are small enough that I can work on them in between milestones work and I'll still make progress on both, instead of stalling one entirely for the other.

* First, I'll finish testing and reviewing the WizardPattern stuff in patternfly-react with @priley86, thanks to a cherry-pick from him and a few remaining minor tasks on my list, it shouldn't take long.
* Then, I'll convert our existing usage of Wizard here in v2v to use the new breaking update to Wizard in https://github.com/patternfly/patternfly-react/pull/268. Also (possibly a separate PR) I will do some general cleanup that I've been trying to get merged ever since I shoved it in with this massive PR.
* Finally, I'll complete the core goal of this refactor, and reduce all the code duplication down into usage of WizardPattern. Whether we use the Stateful or Stateless form of the WizardPattern component doesn't really matter, whichever one we are prepared to integrate more quickly would be my vote. This may be one or multiple PRs, I'll have to see how it makes sense to break it down.

**Comment by priley86** [comment]
this sounds good @mturley 👍

**Comment by mturley** [comment]
This PR is getting closed, because the mountain of rebase conflicts is just too much and I straight up started this refactor over on top of `alpha`.

**Pull request closed without merging**
