### PR TITLE
Move planwizardvmstep table header into component for equal padding

### LINKED ISSUE #295: Fix alignment issues on Step 2 of the Migration Plan Wizard
Everything should be left aligned on the wizard page 
- Title
- Filter Control
- Horizontal Separator
- Table
- "# VMs" label

image

### PR DESCRIPTION
**Pull request by AllenBW**
closes #295

### Where we're now at...
screen shot 2018-05-16 at 7 43 38 am

### Seems to align with pf documentation for toolbar filter control
screen shot 2018-05-16 at 7 44 54 am

[http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/
](http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/
)

### CODE REVIEW

**Comment by priley86** [comment]
🏅 🏅 🏅

**Comment by AllenBW** [comment]
@priley86 @serenamarie125 there's an outstanding question on if the desire is to override pfr and pf-design... Agreed, totally doable, but wanted to get the authorization to defy in place patterns in writing

**Comment by serenamarie125** [comment]
> wait a minute here - didn't @serenamarie125 say to remove paddings on the filter dropdown / right hand search? this is an override from PF React...but it can be done if needed.

I was incorrect (my bad!).  This is spot on 👌

**Comment by priley86** [comment]
woohoo!! lgtm

image

**Comment by AllenBW** [comment]
You goofy sonofahgun ♥ ♥ ♥

**Pull request merged**
