### PR TITLE
update migrations-in-progress url

### PR DESCRIPTION
**Pull request by priley86**
really funny 😸 

@AparnaKarve can you confirm these URLs for us please?

### CODE REVIEW

**Comment by priley86** [comment]
also - may need to review response data... 

screen shot 2018-03-02 at 5 10 12 pm

**Comment by priley86** [comment]
another update:

`"filter[]=state='active'"` will never be visible locally... (b/c the backend will take it from `pending` to `active` for us, but this won't happen on our machines). May need to investigate further next week...

**Comment by priley86** [comment]
I think the best option may be to show another row of cards for `pending` status - per Aparna - a background queue will change the request to `active` ... so I believe we should poll the status of migrations every few seconds and update the Overview dashboard appropriately.

**Comment by AparnaKarve** [comment]
LGTM -- Merging

**Pull request merged**
