### PR TITLE
Remove unused test directory

### PR DESCRIPTION
**Pull request by ZitaNemeckova**
Remove directory test that contains new Rails app.

Removing setting of specs as `bundle exec rake test` isn't working:
```
rake aborted!
LoadError: cannot load such file -- miq_v2v_ui_plugin
/Users/zita/Desktop/ManageIQ/miq_v2v_ui_plugin/test/migration/config/application.rb:6:in `require'
/Users/zita/Desktop/ManageIQ/miq_v2v_ui_plugin/test/migration/config/application.rb:6:in `<top (required)>'
/Users/zita/Desktop/ManageIQ/miq_v2v_ui_plugin/test/migration/Rakefile:4:in `require_relative'
/Users/zita/Desktop/ManageIQ/miq_v2v_ui_plugin/test/migration/Rakefile:4:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/tasks/engine.rake:3:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/tasks/engine.rake:3:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/tasks/engine.rake:2:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/tasks/engine.rake:72:in `<top (required)>'
/Users/zita/Desktop/ManageIQ/miq_v2v_ui_plugin/Rakefile:18:in `load'
/Users/zita/Desktop/ManageIQ/miq_v2v_ui_plugin/Rakefile:18:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => load_app
(See full trace by running task with --trace)
```

### CODE REVIEW

**Comment by ZitaNemeckova** [comment]
@priley86 It would be better to merge it :) It removes second Rails application that was somehow generated to directory test. It's not only unused it's a duplicate. So two reasons to get rid of it :)

>Code is the enemy. It can go wrong. And it needs maintenance. Write less code. Delete code.

I would go with this philosophy :)

**Comment by AparnaKarve** [comment]
@priley86 In the top comment, @ZitaNemeckova mentioned that  `bundle exec rake test` isn't working.

We would need `bundle exec rake test` if down-the-line we decide to add Rails controllers and the tests for those controllers in this plugin. So for that reason alone, I would get rid of it.
@ZitaNemeckova have you confirmed that sans all the extra test files, `bundle exec rake test` works properly? If yes, we can merge this after the summit.
Thanks.

**Comment by AparnaKarve** [comment]
@ZitaNemeckova Ok, thanks for clarifying the above (bundle exec rake test isn't working at all)

**Comment by martinpovolny** [comment]
@priley86 : Ping?

**Pull request merged**
